import api from './axiosInstance';

export const coinAPI = {
  getAll: (params) => api.get('/coins', { params }),
  create: (data) => api.post('/coins', data),
  getById: (id) => api.get(`/coins/${id}`),
  replace: (id, data) => api.put(`/coins/${id}`, data),
  update: (id, data) => api.patch(`/coins/${id}`, data),
  delete: (id) => api.delete(`/coins/${id}`),
  exists: (id) => api.get(`/coins/exists/${id}`),
  latest: (params) => api.get('/coins/latest', { params }),
  trending: (params) => api.get('/coins/trending', { params }),
  recent: (params) => api.get('/coins/recent', { params }),
  random: (params) => api.get('/coins/random', { params }),
  oldest: (params) => api.get('/coins/oldest', { params }),
  newest: (params) => api.get('/coins/newest', { params }),
  topMarketCap: (params) => api.get('/coins/top-market-cap', { params }),
  topVolume: (params) => api.get('/coins/top-volume', { params }),
  topGainers: (params) => api.get('/coins/top-gainers', { params }),
  topLosers: (params) => api.get('/coins/top-losers', { params }),
  sort: (path, params) => api.get(path, { params }),
  filter: (path, params) => api.get(path, { params }),
  byName: (name) => api.get(`/coins/name/${name}`),
  bySymbol: (symbol) => api.get(`/coins/symbol/${symbol}`),
  byRank: (rank) => api.get(`/coins/rank/${rank}`),
  byMonth: (month) => api.get(`/coins/month/${month}`),
  byDate: (date) => api.get(`/coins/date/${date}`),
  performance: (coinId) => api.get(`/coins/performance/${coinId}`),
  volatility: (coinId) => api.get(`/coins/volatility/${coinId}`),
  marketCap: (coinId) => api.get(`/coins/market-cap/${coinId}`),
  volume: (coinId) => api.get(`/coins/volume/${coinId}`),
  returns: (coinId) => api.get(`/coins/returns/${coinId}`),
  price: (coinId) => api.get(`/coins/price/${coinId}`),
  history: (coinId, month) =>
    month ? api.get(`/coins/history/${coinId}/${month}`) : api.get(`/coins/history/${coinId}`),
  compare: (coin1, coin2, coin3) =>
    coin3
      ? api.get(`/coins/compare/${coin1}/${coin2}/${coin3}`)
      : api.get(`/coins/compare/${coin1}/${coin2}`),
  recommendations: (params) => api.get('/coins/recommendations', { params }),
  predictions: (params) => api.get('/coins/predictions', { params }),
  heatmap: (params) => api.get('/coins/heatmap', { params }),
  marketStatus: () => api.get('/coins/market-status'),
  portfolioSimulate: (params) => api.get('/coins/portfolio/simulate', { params }),
  topMonthlyPerformance: (params) => api.get('/coins/performance/top-monthly', { params }),
  topYearlyPerformance: (params) => api.get('/coins/performance/top-yearly', { params }),
  highVolatilityAlerts: (params) => api.get('/coins/alerts/high-volatility', { params }),
  marketDropAlerts: (params) => api.get('/coins/alerts/market-drop', { params }),
  report: (data) => api.post('/coins/report', data),
  exportCsv: () => api.get('/coins/export/csv', { responseType: 'blob' }),
  exportJson: () => api.get('/coins/export/json', { responseType: 'blob' }),
  systemHealth: () => api.get('/coins/system/health'),
  systemVersion: () => api.get('/coins/system/version'),
  systemConfig: () => api.get('/coins/system/config'),
  bulkCreate: (data) => api.post('/coins/bulk-create', data),
  bulkUpdate: (data) => api.patch('/coins/bulk-update', data),
  bulkDelete: (data) => api.delete('/coins/bulk-delete', { data }),
  clearCache: () => api.get('/coins/cache/clear'),
};
